### ISSUE TITLE
update_db() not work with calculate_player_stats()?

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#279]
```
update_db()

connection <- dbConnect(SQLite(), "./pbp_db")
connection

dbListTables(connection)

dbListFields(connection, "nflfastR_pbp") %>%
  head(10)
  
pbp <- tbl(connection, "nflfastR_pbp")

calculate_player_stats(pbp, weekly = FALSE)

```
Error in decode_ids_cpp(player_ids) : can not find 'passer_id'

so i cannot use the function calculate_player_stats()

```
pbp <- nflfastR::load_pbp(2020)

weekly <- calculate_player_stats(pbp, weekly = TRUE)
dplyr::glimpse(weekly)
```
but everything is fine with load_pbp()

Do load_pbp() and update_db() not create same datebase?

**Comment by tanho63** [comment]
they do create the same database. pbp doesn't have a player_id column because it describes multiple kinds of ids (passer, receiver, rusher, defender etc). you should not need to run a select on pbp before passing it into calculate_player_stats - just do pbp %>% filter(season == 2020) %>% collect() %>% calculate_player_stats()

**Comment by ak47twq** [comment]
> they do create the same database. pbp doesn't have a player_id column because it describes multiple kinds of ids (passer, receiver, rusher, defender etc). you should not need to run a select on pbp before passing it into calculate_player_stats - just do pbp %>% filter(season == 2020) %>% collect() %>% calculate_player_stats()

ok thx!!! now everything works!!! thx a lot!!
