### ISSUE TITLE
2021_18_TEN_HOU score in rbsdm.com not correct.

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflfastR#311]
![image](https://user-images.githubusercontent.com/72854702/149623982-976b483e-99ab-4523-9173-05b32c45995f.png)
![image](https://user-images.githubusercontent.com/72854702/149624009-2d8b9240-51cf-4f73-a20e-667ea3c306ac.png)
https://rbsdm.com/stats/box_scores/?_inputs_&type=%22reg%22&away=%22TEN%22&home=%22HOU%22&year=%222021%22

the score is not correct. dont know what went wrong.

**Comment by guga31bb** [comment]
Thank you! 

The issue is that NFL is slow to correct overturned touchdowns and this requires manual re-scrapes later in the week. If this ever happens again, please leave an issue like this and I can fix- thanks!
![image](https://user-images.githubusercontent.com/1425357/149627690-0c1535af-b106-4fb3-b76f-e9cca557a31c.png)
