### ISSUE TITLE
Issue Recording EPA for Games in Buffalo Specifically

### ISSUE THREAD

**Issue by jacole3** [nflverse/nflfastR#331]
NOTE: The following code was written while using data from NFLFastR version 4.3.0. Any future versions of NFLFastR may not have the same problem.

I've come across an issue in NFLFastR data that seems to specifically be targeted toward what's now known as Highmark Stadium (the Bills' home field). Using the below code, I removed all non-football sequences from the NFLFastR data (e.g. timeouts, descriptions of player injuries, "END OF GAME" notifications, etc.):

seasons <- 1999:2021
pbp <- nflfastR::load_pbp(seasons)
pbp$play_id <- 1:nrow(pbp)

Useless_NoSnap <- pbp %>% 
  filter( (penalty == 0 & 
             (timeout > 0 & play_type == "no_play")) |
            (is.na(play_type) & 
               ((is.na(play_type_nfl) & !str_detect(desc, "(enforced)") & !str_detect(desc, "(Enforced)") & !str_detect(desc, "(ENFORCED)")) | 
                  (play_type_nfl != "PENALTY" & play_type_nfl != "FREE_KICK" & play_type_nfl != "KICK_OFF" & 
                     !str_detect(desc, "(enforced)") & !str_detect(desc, "(Enforced)") & !str_detect(desc, "(ENFORCED)")))) )
Useless_NoSnap_Vec <- Useless_NoSnap$play_id

pbp <- pbp %>% filter(!play_id %in% Useless_NoSnap_Vec)
pbp$play_id <- 1:nrow(pbp)

From there, I looked all such plays in regulation (excluding play_type == "qb_kneel" situations) where the offensive team had an NA value listed for EPA:

View(pbp %>% filter(is.na(epa) & qtr <= 4 & play_type != "qb_kneel"))

Remarkably, 44 of the 54 plays listed in this data set are ones that took place in Buffalo (with the other 10 coming in New England). Needless to say, this is far too heavy of a skew in one team's direction to be due to random chance. If any NFLFastR pioneers such as @guga31bb or @mrcaseb have any insight as to the cause of the problem, that would be interesting. It is also noteworthy that every play listed is the final play of the game in question (therefore, EPA can be manually calculated by combining EP entering the play with the game's final score).

<img width="643" alt="Screen Shot 2022-06-06 at 4 13 00 PM" src="https://user-images.githubusercontent.com/39979582/172264199-0d9c1bc6-53bf-4c41-88ce-eeb8ea45df25.png">

**Comment by mrcaseb** [comment]
It is no surprise that BUF and NE home games are affected. The stat keepers in these stadiums are knows as "over motivated". The Patriots keeper states a lot of additional info in play descriptions and the BUF keeper sometimes just does what he wants in play descriptions. 

This is also the problem in this case. All of these plays happened close to the end of the game in the 4th quarter. Since epa is the problem, we have to check the next play. 

Here are ids and desc of the next plays [bad_play_descs.csv](https://github.com/nflverse/nflfastR/files/8852897/bad_play_descs.csv)

<img width="656" alt="image" src="https://user-images.githubusercontent.com/38586519/172373025-cccf9043-be75-4236-ab7d-c6906c77b244.png">

Looks like we need some additional end of game detection phrases

**Comment by mrcaseb** [comment]
wpa shouldn't be affected because we use this variable

https://github.com/nflverse/nflfastR/blob/ddf2f3450a9c6cd04e470959cc841911d34fc2d3/R/helper_add_ep_wp.R#L802-L805

We should do the same with epa @guga31bb

**Comment by guga31bb** [comment]
Yep I should have fixed this when doing the same for WP but didn't think to do it
