### ISSUE TITLE
EP might be dumb for neutral site games

### ISSUE THREAD

**Issue by guga31bb** [nflverse/nflfastR#346]

**Comment by mrcaseb** [comment]
I think we could change this line https://github.com/nflverse/nflfastR/blob/4d605969e9d199b98367dd75013189fa6692d46b/R/helper_add_nflscrapr_mutations.R#L620

to

```r
home = dplyr::if_else(.data$posteam == .data$home_team & .data$location == "Home", 1, 0),
```

However, this would only work in the ep/wp workflow as long as we don't select the final variables because location is not selected in that process. Every other function that call `make_model_mutations()` would potentially fail because standard pbp doesn't include `location`. So if we want to go that way, we have to add location as variable to the final pbp data.

**Comment by guga31bb** [comment]
I think that's easy to deal with, just need something afterwards that's along the lines of:
```
if ("location" %in% names(pbp)) {

  pbp <- pbp %>%
    dplyr::mutate(
      home = dplyr::if_else(.data$location == "Neutral", 0, .data$home)
  )

}
```

**Comment by mrcaseb** [comment]
I think xpass, xyac and the ep calculator use `make_model_mutations()` and the returned `home` value as well. Won't this mess them up?

**Comment by guga31bb** [comment]
,,,,,
